// GENERATED by scripts/field-cad/emit-dims.mjs — DO NOT HAND-EDIT. Re-run `npm run field-cad`.
//
// THE BIOBUZZ FIELD'S DIMENSIONS, MEASURED OFF FIRST's OWN FIELD CAD.
// Owner ruling, 2026-09-18: "The CAD is authoritative for dimensions." Where a figure in the
// V1 Competition Manual disagrees with a number below, the number below wins and the figure is
// kept in `config.ts` as history. `docs/biobuzz/field-cad-audit.md` is the measurement report.
//
// source STEP : FIRST field CAD v26-27.2 (2026-09-15), sha256 5e768b731f1ec8dcd14debba53225c43718877923c351ce08504305f68f7fe00
//               captured 2026-09-17 from https://ftc-resources.firstinspires.org/ftc/archive/2027/field/field-cad-step
// measured by : scripts/field-cad/convert.py → public/models/biobuzz/field-measurements.json
//               sha256 3d8c1d4097bfb7536aadc925fc1efcc0e00b612678c41488ca6a40eebd9da6f0
// frame       : the sim frame — inches, origin at the field centre on the tile top surface,
//               +x audience right, +y away from the audience. Rounded to 1e-3 in.
//
// ── EVERY VALUE, AND WHERE IT COMES FROM ────────────────────────────────────────────────────
// FIELD_HALF   70.674  = mean |walls.innerFace.{left,right,rear,audience}| over 4 faces, worst residual 0in (the CAD's four faces ARE symmetric). Interior span 141.348in, against the 144 the manual's "12 ft field" implies.
// WALL_H       11.644  = walls.assemblyZ[1] (the top rail's top). Glass alone spans z 0.09..10.965 (walls.glassZ).
// TILE_PITCH   23.528  = tiles.pitch (a real FTC soft tile is 23.53 in on centre, not 24 — this is the whole field-size finding).
// TILE_SEAMS   7 lines = the two perimeter edges and the five tile JOINTS, each the middle of the band where two columns'
//                tabs overlap (tiles.x0Seams[i] .. −x0Seams[6−i], by the layout's point symmetry). The joints are evenly spaced at
//                23.502in (residual 0); the outer tiles are cut straight and run 23.581in. TILE_PITCH is the mean.
// TILE_SPAN_HALF 70.585  = mean |tiles.extent.{x,y}|, residual 0in — the tiles stop 0.089in short of the wall.
// FLOWER_D     2.629  = FIELD_HALF − mean |top-ring bore centre, wall-normal axis| (68.045, residual 0in over 4 flowers).
//                The old hand-entered 2.54 is 0.089in off — the flower was never misplaced, the FIELD was.
// FLOWER_ALONG 23.392  = mean |bore centre, along-wall axis| (residual 0in). The old ±24 was the 24-in tile seam; the real
//                seam is at 23.392, which is one tile of accumulated pitch error.
// FLOWER_RING_D top 4.171 / mid 3.896 / lower 3.222  = mean least-squares bore diameters (residuals 0/0/0in).
// FLOWER_EXTENT_Z [-0.649, 22.654]  = mean flowers[].extent.z — the WHOLE assembly (the top is the purple backstop, the
//                bottom is the under-field bracket). FLOWER_RING_Z below is the per-PLATE band, which is what BB_FLOWER_TOP_Z reads now.
// FLOWER_RING_Z top [20.254, 21.404] / mid [3.904, 5.254] / lower [-0.199, 0.354]  = mean of each PLATE's
//                own z band (worst residual 0in). The clear gap between the lower plate's TOP and the mid plate's UNDERSIDE is
//                3.55in — Fig 9-12's 3.55-in RETRIEVAL OPENING, derived rather than assumed, and the sharpest confirmation in this file.
//                BB_FLOWER_TOP_Z was the manual's 21.5 (Δ 0.096); BB_FLOWER_MID_Z an APPROX 3.98 (Δ 0.076); BB_FLOWER_FLOOR_Z an APPROX 0.43 (Δ 0.076).
// FLOWER_FOOT  5.951 × 5.013  = the union of the three ring plates' own footprints, along the wall × into the field (residuals
//                0/0in). The hand-typed 6 × 4.9 was within 0.05 / 0.11. This is the on-tile solid a robot meets; flowers[].extent
//                is NOT — it carries the backstop above the top plate and the bracket behind the wall plane.
// HIVE.PIVOT_X 12.75 / PIVOT_Z 43.95 / TILT_DEG 30  = mean |trays[].pivot[0]| (residual 0), hive.pivotZ,
//                mean |trays[].captureThetaDeg| (residual 0). The tilt is EXACTLY 30° — audit §4.1 proves it by un-tilting the
//                0.020-in back skin and watching it collapse to its own thickness.
// HIVE cells   ARM 15.519 · LEN 42.788 · CELL_W 20.141 · CELL_D 11.75 · CELL_H 13.997  — all TRUE lengths along the bar,
//                from the mean of the 4 measured cells (trays[].cells[]; residuals xHalf 0, near 0, far 0,
//                floor 0, top 0in). ARM = (near+far)/2, LEN = 2·far, CELL_D = far−near, CELL_H = top−floor.
//                config.ts's PLAN lengths are these × cos 30°.
// HIVE.OPEN_Z  [53.375, 65.497]  = mean hive.openingZ[] (residuals 0/0in) — the up cell's mouth at rest.
//                The manual's Fig 9-10 prints [53.5, 65.6]; the CAD agrees to 0.13 in, which is why this one is a confirmation, not a move.
// HIVE.DOWN_FLOOR_Z 31.981 / LOWEST_Z 30.652  = mean hive.downCellFloorZ[] (residual 0in) and
//                hive.lowestStructureZAtRest.z ("am-5866-blue: Blue Goal Rib"). Fig 9-10's 25.5 is 6.481in low: one rigid bar
//                cannot put the up mouth at 53.4 and the down floor at 25.5 at the same time. A 29-in robot CLEARS the structure.
// TAPE.gardenSupplement    NOT MEASURED — one 0.573 x 2 in patch per alliance,
//                bridging the GARDEN band's corner end to the perimeter face so the drawn band covers the whole of
//                `GARDEN` (which snaps that edge onto the wall). Its own group: `TAPE.garden` stays the CAD's, and
//                the zone rectangles below are built from `TAPE.garden` alone, so this cannot move a rule.
// TAPE         16 strips, every one 1.000 in wide, grouped by the nominal length in the STEP part name
//                (22.69 = a GARDEN band half, 20.69 = a LOADING ZONE's inner edge, 11 = a depth edge, 54/94.82 = the ALLIANCE AREA).
//                A zone edge that is a WALL carries NO tape (audit §5) — the on-tile strips stop 0.573in clear of the inner face.
// LZ/GARDEN/ALLIANCE_AREA  = the union of that group's strips, with any edge within 1.25in of a wall face snapped ONTO it (moved: red garden 0.573in, blue garden 0.573in, red loadingZone 0.573in, blue loadingZone 0.573in, red allianceArea 0.976in, blue allianceArea 0.976in).
//                "Bounded by tape and the wall, tape included" (§9.3) is exactly that rule: the tape's own outer face is the zone edge
//                everywhere except where the perimeter is.
//
// ✅ CLOSED 2026-09-18 (Day 2 lane A): the flower's three RING PLATE z bands and its on-tile
// FOOTPRINT used to be measured in the audit (§6) but not carried by `field-measurements.json`,
// so `BB_FLOWER_TOP_Z`, `BB_FLOWER_MID_Z`, `BB_FLOWER_FLOOR_Z` and `BB_FLOWER_FOOT` stayed hand-typed.
// `convert.py` now separates the plates from the assembly and `FLOWER_RING_Z` / `FLOWER_FOOT`
// below are the measurements; `config.ts` reads them and no flower dimension is APPROX any more.
// The GLBs are byte-identical across that change — the plates were always in the visual export.

/** an axis-aligned field region, world inches. Structurally identical to `config.ts`'s
 * `BbRect` — declared here so this module imports nothing at all. */
export interface BbGenRect {
  readonly x0: number;
  readonly x1: number;
  readonly y0: number;
  readonly y1: number;
}

/** half the clear span inside the perimeter (in) — the wall's INNER face. */
export const FIELD_HALF = 70.674;

/** the four measured inner faces, unaveraged — what an agreement check compares a collider to. */
export const WALL_FACE: { readonly left: number; readonly right: number; readonly rear: number; readonly audience: number } = {
  left: -70.674,
  right: 70.674,
  rear: 70.674,
  audience: -70.674,
};

/** the perimeter assembly's own height above the tiles (in) — rail top, not the physics wall. */
export const WALL_H = 11.644;
/** the polycarbonate pane's own z span (in). */
export const WALL_GLASS_Z: readonly [number, number] = [0.09, 10.965];

/** soft-tile pitch on centre (in) — the mean seam spacing. NOT 24. */
export const TILE_PITCH = 23.528;
/** half the tiled floor's own span (in) — the tiles stop short of the wall. */
export const TILE_SPAN_HALF = 70.585;
/** the seven seam lines, on both axes (in): the two perimeter edges and the five tile joints — see the header. */
export const TILE_SEAMS: readonly number[] = [-70.585, -47.004, -23.502, 0, 23.502, 47.004, 70.585];

/** a FLOWER's ring-bore centre, off its own wall's inner face (in). */
export const FLOWER_D = 2.629;
/** a FLOWER's station ALONG its wall (in), from the field centre. */
export const FLOWER_ALONG = 23.392;
/** the four ring-bore centres, in the sim frame. */
export const FLOWERS: readonly { readonly id: string; readonly wall: 'left' | 'rear' | 'right' | 'audience'; readonly x: number; readonly y: number; readonly nearest: 'red' | 'blue' }[] = [
  { id: 'F1', wall: 'left', x: -68.045, y: -23.392, nearest: 'red' },
  { id: 'F2', wall: 'rear', x: -23.392, y: 68.045, nearest: 'red' },
  { id: 'F3', wall: 'right', x: 68.045, y: 23.392, nearest: 'blue' },
  { id: 'F4', wall: 'audience', x: 23.392, y: -68.045, nearest: 'blue' },
];
/** the three ring plates' bore DIAMETERS (in): what fits through the top, middle and bottom. */
export const FLOWER_RING_D: { readonly top: number; readonly mid: number; readonly lower: number } = { top: 4.171, mid: 3.896, lower: 3.222 };
/** each ring PLATE's own z band (in), [underside, top face]. The tube bottom to top is the
 * lower plate, the retrieval opening, the mid plate, the scoring volume, the top plate. */
export const FLOWER_RING_Z: {
  readonly top: readonly [number, number];
  readonly mid: readonly [number, number];
  readonly lower: readonly [number, number];
} = {
  top: [20.254, 21.404],
  mid: [3.904, 5.254],
  lower: [-0.199, 0.354],
};
/** the RETRIEVAL OPENING's own z span (in) — the clear gap between the lower plate's top face
 * and the mid plate's underside, 3.55 in tall against Fig 9-12's 3.55. */
export const FLOWER_RETRIEVAL_Z: readonly [number, number] = [0.354, 3.904];
/** the on-tile FOOTPRINT of a flower's ring plates (in) — along its wall × into the field. */
export const FLOWER_FOOT: { readonly along: number; readonly deep: number } = { along: 5.951, deep: 5.013 };
/** the whole flower assembly's z span (in) — backstop top, under-field bracket bottom. */
export const FLOWER_EXTENT_Z: readonly [number, number] = [-0.649, 22.654];

/** the HIVE, in TRUE lengths along its own bar (in) — `config.ts` projects them by cos 30°. */
export const HIVE: {
  readonly PIVOT_X: number;
  readonly PIVOT_Z: number;
  readonly TILT_DEG: number;
  readonly ARM: number;
  readonly LEN: number;
  readonly CELL_W: number;
  readonly CELL_D: number;
  readonly CELL_H: number;
  readonly CELL_NEAR: number;
  readonly CELL_FAR: number;
  readonly CELL_FLOOR_W: number;
  readonly CELL_TOP_W: number;
  readonly OPEN_Z: readonly [number, number];
  readonly DOWN_FLOOR_Z: number;
  readonly LOWEST_Z: number;
  readonly UP_STAGED: { readonly red: 'north' | 'south'; readonly blue: 'north' | 'south' };
} = {
  PIVOT_X: 12.75,
  PIVOT_Z: 43.95,
  TILT_DEG: 30,
  ARM: 15.519,
  LEN: 42.788,
  CELL_W: 20.141,
  CELL_D: 11.75,
  CELL_H: 13.997,
  CELL_NEAR: 9.644,
  CELL_FAR: 21.394,
  CELL_FLOOR_W: -1.468,
  CELL_TOP_W: 12.529,
  OPEN_Z: [53.375, 65.497],
  DOWN_FLOOR_Z: 31.981,
  LOWEST_Z: 30.652,
  UP_STAGED: { red: 'south', blue: 'north' },
};

/** gaffer tape width (in) — the only width on this field. */
export const TAPE_W = 1;

/** every tape STRIP, as the rectangle the CAD puts it at. A renderer draws THESE, not an
 * outline of the zone: the wall-bounded edge of a zone carries no tape. */
export const TAPE: {
  readonly loadingZone: { readonly red: readonly BbGenRect[]; readonly blue: readonly BbGenRect[] };
  readonly garden: { readonly red: readonly BbGenRect[]; readonly blue: readonly BbGenRect[] };
  readonly allianceArea: { readonly red: readonly BbGenRect[]; readonly blue: readonly BbGenRect[] };
  /** NOT CAD — see the header. Drawn beside `garden`; never part of a zone rectangle. */
  readonly gardenSupplement: { readonly red: readonly BbGenRect[]; readonly blue: readonly BbGenRect[] };
} = {
  loadingZone: {
    red: [
      { x0: -70.101, x1: -59.101, y0: 23.907, y1: 24.907 },
      { x0: -70.101, x1: -59.101, y0: 45.599, y1: 46.599 },
      { x0: -60.101, x1: -59.101, y0: 24.907, y1: 45.599 },
    ],
    blue: [
      { x0: 59.101, x1: 70.101, y0: -46.599, y1: -45.599 },
      { x0: 59.101, x1: 60.101, y0: -45.599, y1: -24.907 },
      { x0: 59.101, x1: 70.101, y0: -24.907, y1: -23.907 },
    ],
  },
  garden: {
    red: [
      { x0: -70.101, x1: -47.409, y0: -70.101, y1: -69.101 },
      { x0: -70.101, x1: -47.409, y0: -69.101, y1: -68.101 },
    ],
    blue: [
      { x0: 47.409, x1: 70.101, y0: 68.101, y1: 69.101 },
      { x0: 47.409, x1: 70.101, y0: 69.101, y1: 70.101 },
    ],
  },
  allianceArea: {
    red: [
      { x0: -125.65, x1: -71.65, y0: -48.41, y1: -47.41 },
      { x0: -125.65, x1: -124.65, y0: -47.41, y1: 47.41 },
      { x0: -125.65, x1: -71.65, y0: 47.41, y1: 48.41 },
    ],
    blue: [
      { x0: 71.65, x1: 125.65, y0: -48.41, y1: -47.41 },
      { x0: 71.65, x1: 125.65, y0: 47.41, y1: 48.41 },
      { x0: 124.65, x1: 125.65, y0: -47.41, y1: 47.41 },
    ],
  },
  gardenSupplement: {
    red: [
      { x0: -70.674, x1: -70.101, y0: -70.101, y1: -68.101 },
    ],
    blue: [
      { x0: 70.101, x1: 70.674, y0: 68.101, y1: 70.101 },
    ],
  },
};

/** the LOADING ZONE — the side wall and three 1-in tapes, tape included (§9.3). */
export const LZ: { readonly red: BbGenRect; readonly blue: BbGenRect } = {
  red: { x0: -70.674, x1: -59.101, y0: 23.907, y1: 46.599 },
  blue: { x0: 59.101, x1: 70.674, y0: -46.599, y1: -23.907 },
};

/** the GARDEN — the 2-in band of two tapes, run into the alliance corner and closed by the two walls. */
export const GARDEN: { readonly red: BbGenRect; readonly blue: BbGenRect } = {
  red: { x0: -70.674, x1: -47.409, y0: -70.674, y1: -68.101 },
  blue: { x0: 47.409, x1: 70.674, y0: 68.101, y1: 70.674 },
};

/** the ALLIANCE AREA, on the gym floor OUTSIDE the perimeter (three strips, the field side open). */
export const ALLIANCE_AREA: { readonly red: BbGenRect; readonly blue: BbGenRect } = {
  red: { x0: -125.65, x1: -70.674, y0: -48.41, y1: 48.41 },
  blue: { x0: 70.674, x1: 125.65, y0: -48.41, y1: 48.41 },
};
